### ISSUE TITLE
Dynamics masks - problem

### ISSUE THREAD

**Issue by neopheus** [beholdr/maska#17]
Hi, 

I have a problem with multiple masks :
` data-mask='["AA-###-AA", "#### AAA ##"]'`

the first mask works but the second mask does not work

Example : https://codepen.io/neopheus/pen/QWKYaKZ

Have you a solution ?

**Comment by beholdr** [comment]
Hi, dynamic masks are for simpler cases like `['##-###-##', '#### ### ##']` where you use same tokens but with different formating. Because you can’t step from first mask to second when they have so different structure like yours.

You could use some universal tokens like `['XX-XXX-XX', 'XXXX XXX XX']` to get formatting but it will not limit input symbols.
