### ISSUE TITLE
Masks don't work on input type of number

### ISSUE THREAD

**Issue by tripleplayj** [beholdr/maska#5]
Hello,

Sorry to raise another issue, but I came across this one today. If the input type is number, the masks seem not apply. It allows all the things that html5 number input allows. For example in your demo, if I change the input type to "number" it allows me to put in "e", "-",  and "." even though the mask is `#*`. Any thoughts on this? Thanks for any help.

**Comment by beholdr** [comment]
Yeah, you right. I've examined work with `number` input and it's not so simple because of browser validation of numbers in such case. You can read about it [here](https://stackoverflow.com/questions/18852244/how-to-get-the-raw-value-an-input-type-number-field). I've made some fixes to 1.1.3 version, but it still works little weird in Firefox, for example, because it does not support `beforeinput` event yet.

If you only need `number` input for different keyboard type, I suggest to use attribute `inputmode` instead of `number` type.
