### ISSUE TITLE
Error while using with Nuxt 3 and Vuetify 3

### ISSUE THREAD

**Issue by desenvolvimento02jocc** [beholdr/maska#97]
**Describe the bug**
Installed maska as a plugin while using Nuxt 3 and Vuetify 3.0.3 and i'm getting and im getting some issues.

**Steps to reproduce**
1. Install it as a global plugin in Nuxt 3 while using Vuetify 3.0.3
```js
import { vMaska } from "maska";

export default defineNuxtPlugin((nuxtApp) => {
  
    nuxtApp.vueApp.directive('maska', vMaska);
  });
```

2. Use it in a component 
```html
  <v-text-field v-maska data-maska="#-#" density="compact" label="CNPJ"
                            v-model="companyData.cnpj" />
```
![image](https://user-images.githubusercontent.com/87676055/206008574-fc0c7a87-b5df-46c9-9805-5cb98d3c123b.png)

![image](https://user-images.githubusercontent.com/87676055/206008622-dcf06861-ca8d-41e5-8fa1-0af280f8ae78.png)

**Comment by desenvolvimento02jocc** [comment]
Same happens when using it locally.

**Comment by 25Das** [comment]
I had this same problem, and that's why you're using it in a component, I couldn't get it to work that way either, so what I did was use the mask options.

I don't know how components work in vuetify but I did it this way with a common custom component.

I declared a variable computed with the mask options.
`
computed: {
      cnpjMaskOptions() {
        return {
          mask: '##.###.###/####-##',
          onMaska: ({ unmasked }) => (this.cnpj = unmasked),
        };
      },
}
`

Then I passed them as a prop to the component.
`
<DefaultInput
                v-model="cnpj"
                :mask-options="cnpjMaskOptions"
                label="CNPJ:"
                type="text"
                name="cnpj"
              />
`

So in the component I passed as options to the v-maska directive.
`
<input
      v-maska:[maskOptions]
      :type="type"
      :name="name"
      :value="modelValue"
    />
`

And in the onMaska event of the mask options I can retrieve the value, masked or not.

This is the workaround that I found to make it work with custom components but i do not know if it will work with any builtin or handcraft component like with vuetify.

**Comment by beholdr** [comment]
I have fixed this error in v2.0.1. But it still buggy because of Vuetify events.
And to make it work with Vuetify 3.x you should use options argument because they don't pass `data-` props to native input:

``` html
<script setup>
const options = { mask: '#-#' };
</script>

<template>
  <div>
    <v-text-field v-maska:[options] />
  </div>
</template>
```

**Comment by jboada** [comment]
Thanks a lot @beholdr , it has helped me a lot right now.

**Comment by 5e** [comment]
Thanks, might be worth putting the Vuetify 3 part in the docs as I was also looking for this fix @beholdr
